//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLYTA.NYP_API {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NYP_API.INYP_WS")]
    public interface INYP_WS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INYP_WS/getStudents", ReplyAction="http://tempuri.org/INYP_WS/getStudentsResponse")]
        System.Data.DataSet getStudents(int OSEP_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INYP_WS/getStudents", ReplyAction="http://tempuri.org/INYP_WS/getStudentsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getStudentsAsync(int OSEP_ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INYP_WSChannel : FLYTA.NYP_API.INYP_WS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NYP_WSClient : System.ServiceModel.ClientBase<FLYTA.NYP_API.INYP_WS>, FLYTA.NYP_API.INYP_WS {
        
        public NYP_WSClient() {
        }
        
        public NYP_WSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NYP_WSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NYP_WSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NYP_WSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getStudents(int OSEP_ID) {
            return base.Channel.getStudents(OSEP_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getStudentsAsync(int OSEP_ID) {
            return base.Channel.getStudentsAsync(OSEP_ID);
        }
    }
}
